services:
  database:
    image: postgres:latest
    container_name: database
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_VERSION=${APP_VERSION}
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database
volumes:
  postgres-data: