name: F1 Assignment Backend CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Install dependencies
        run: ./gradlew dependencies

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Run tests
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Extract version from gradle.properties
        id: gradle-version
        run: |
          VERSION=$(grep "version=" gradle.properties | cut -d'=' -f2)
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: backend/build/libs/f1-${{ env.APP_VERSION }}.jar

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.APP_VERSION }}
          name: Release v${{ env.APP_VERSION }}
          files: ./backend/build/libs/f1-${{ env.APP_VERSION }}.jar
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
