name: Flutter CI/CD

on:
  push:
    branches: [feature/ci-cd]
    paths:
      - "frontend/**"
      - '.github/workflows/frontend.yml'
  workflow_dispatch:

jobs:
  flutter_ci:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.0"
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Run linter
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Generate env.json for Android
        run: |
          echo '{
            "API_URL": "${{ secrets.ANDROID_BASE_URL }}",
            "SEASON_START_YEAR": "${{ secrets.APP_SEASON_START_YEAR }}"
          }' > env.json

      - name: Build Android APK
        run: flutter build apk --release --dart-define-from-file=env.json

      - name: Generate env.json for IOS
        run: |
          echo '{
            "API_URL": "${{ secrets.IOS_BASE_URL }}",
            "SEASON_START_YEAR": "${{ secrets.APP_SEASON_START_YEAR }}"
          }' > env.json

      - name: Build iOS
        run: |
          cd ios
          pod install
          cd ..
          flutter build ios --release --no-codesign --dart-define-from-file=env.json

      - name: Upload Android Build
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: frontend/build/app/outputs/flutter-apk/app-release.apk

      - name: Upload iOS Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: frontend/build/ios/iphoneos
